language: node_js
os: linux
sudo: required
dist: trusty
group: travis_lts
node_js:
  - '9.3.0'
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build:release
  - cp -r ./data/* ./website/
  - npm run deploy
